language: ruby
cache:
  bundler: true
addons:
  postgresql: '9.3'
rvm:
  - 2.1.6
before_script:
  - psql -c 'create database valogy_test;' -U postgres
  - cd spec/dummy/ && RAILS_ENV=test bundle exec rake db:migrate || true
  - cd -
script:
  - bundle exec rake
